### ISSUE TITLE
tile_skybox_img in skyboxengine.py

### ISSUE THREAD

**Issue by yggs1401** [jiupinjia/SkyAR#9]
Hello!

First of all, great work! 
I was wondering if you can explain a little bit the meaning of concat for imgtile and how it works.

Thank you!

**Comment by jiupinjia** [comment]
Hi yggs1401, thanks for your good question. The concat for imgtile is a small trick for building skybox image. In theory, a skybox should have no boundaries. When building a skybox using a single background sky image, say, the "./skybox/jupiter.jpg", we need to relocate the center of the camera-view to the top-left corner of the background image. This is because, when we are performing the affine transform, the origin of the transformation is at the upper left corner of the image. We need to make such an alignment. If you show the background image after the tile, it would be like the following. 
This operation may look a little bit tricky but it does simply the warping a lot. Hope the above explanation will address your concern.

![WeChat Screenshot_20201119141224](https://user-images.githubusercontent.com/51430557/99712632-56270180-2a71-11eb-90b9-cc00450468d0.jpg)

**Comment by yggs1401** [comment]
Thank you for your answer! The origin of the affine transformation is always on the top left corner? Another question is, we apply the transformation matrix on all pixels or just on the origin?

Thank you!

**Comment by jiupinjia** [comment]
> Thank you for your answer! The origin of the affine transformation is always on the top left corner? Another question is, we apply the transformation matrix on all pixels or just on the origin?
> 
> Thank you!

Yes, the origin of an affine transform should be always in the top left corner. Let's say if you want to rotate an image for a certain degree. If you simply apply a rotation matrix to the image data, the rotation would be performed based on the upper left corner of the image, rather than the image center. 
The second question. We apply the transform to all pixels.

**Comment by yggs1401** [comment]
Thank you! Kind regards and stay safe!
